language: node_js
node_js:
  - 6
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  project: ./build/
  domain: macklin.underdown.me
  skip_cleanup: true
branches:
  only:
    - master
